#!/bin/bash
set -e

TEST=$1

if [ -z "$TEST" ]; then
  echo "Uso: $0 <nombre_del_test>"
  exit 1
fi

pushd ${TEST} > /dev/null
make
popd > /dev/null

../build/qemu-system-riscv32 \
  -M noel-srg \
  -nographic \
  -no-reboot \
  -device loader,file=${TEST}/kernel.elf
